/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lanchonete.tela;

import lanchonete.modelo.Pedido;

/**
 *
 * @author Ricardo Brasil
 */
public class TelaPedido extends javax.swing.JFrame {

  private Pedido pedido = new Pedido();
  
  /**
   * Creates new form Pedido
   */
  public TelaPedido() {
    initComponents();
    gerarRelatorio();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    grupoBatataFrita = new javax.swing.ButtonGroup();
    panelPedido = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    lanche = new javax.swing.JComboBox();
    pequeno = new javax.swing.JRadioButton();
    medio = new javax.swing.JRadioButton();
    grande = new javax.swing.JRadioButton();
    panelIngredientes = new javax.swing.JPanel();
    tomate = new javax.swing.JCheckBox();
    cebola = new javax.swing.JCheckBox();
    alface = new javax.swing.JCheckBox();
    picles = new javax.swing.JCheckBox();
    ketchup = new javax.swing.JCheckBox();
    mostarda = new javax.swing.JCheckBox();
    pepino = new javax.swing.JCheckBox();
    barbecue = new javax.swing.JCheckBox();
    panelValorTotal = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    valorTotal = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("SECOND LANCHES");

    panelPedido.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido"));

    jLabel1.setText("Lanche:");

    jLabel2.setText("Batata frita:");

    lanche.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "selecione", "hamburguer", "cheeseburguer" }));
    lanche.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        lancheActionPerformed(evt);
      }
    });

    grupoBatataFrita.add(pequeno);
    pequeno.setText("Pequeno");
    pequeno.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        pequenoItemStateChanged(evt);
      }
    });

    grupoBatataFrita.add(medio);
    medio.setText("Médio");
    medio.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        medioItemStateChanged(evt);
      }
    });

    grupoBatataFrita.add(grande);
    grande.setText("Grande");
    grande.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        grandeItemStateChanged(evt);
      }
    });

    org.jdesktop.layout.GroupLayout panelPedidoLayout = new org.jdesktop.layout.GroupLayout(panelPedido);
    panelPedido.setLayout(panelPedidoLayout);
    panelPedidoLayout.setHorizontalGroup(
      panelPedidoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(panelPedidoLayout.createSequentialGroup()
        .addContainerGap()
        .add(panelPedidoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(panelPedidoLayout.createSequentialGroup()
            .add(jLabel1)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(lanche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(panelPedidoLayout.createSequentialGroup()
            .add(jLabel2)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
            .add(pequeno)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(medio)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(grande)))
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    panelPedidoLayout.setVerticalGroup(
      panelPedidoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(panelPedidoLayout.createSequentialGroup()
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .add(panelPedidoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel1)
          .add(lanche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
        .add(panelPedidoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel2)
          .add(pequeno)
          .add(medio)
          .add(grande)))
    );

    panelIngredientes.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingredientes"));

    tomate.setText("Tomate");
    tomate.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        tomateItemStateChanged(evt);
      }
    });

    cebola.setText("Cebola");
    cebola.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        cebolaItemStateChanged(evt);
      }
    });

    alface.setText("Alface");
    alface.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        alfaceItemStateChanged(evt);
      }
    });

    picles.setText("Picles");
    picles.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        piclesItemStateChanged(evt);
      }
    });

    ketchup.setText("Ketchup");
    ketchup.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        ketchupItemStateChanged(evt);
      }
    });

    mostarda.setText("Mostarda");
    mostarda.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        mostardaItemStateChanged(evt);
      }
    });

    pepino.setText("Pepino");
    pepino.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        pepinoActionPerformed(evt);
      }
    });

    barbecue.setText("Barbecue");
    barbecue.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        barbecueItemStateChanged(evt);
      }
    });

    org.jdesktop.layout.GroupLayout panelIngredientesLayout = new org.jdesktop.layout.GroupLayout(panelIngredientes);
    panelIngredientes.setLayout(panelIngredientesLayout);
    panelIngredientesLayout.setHorizontalGroup(
      panelIngredientesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(panelIngredientesLayout.createSequentialGroup()
        .addContainerGap()
        .add(panelIngredientesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(panelIngredientesLayout.createSequentialGroup()
            .add(tomate)
            .add(18, 18, 18)
            .add(cebola))
          .add(panelIngredientesLayout.createSequentialGroup()
            .add(ketchup)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
            .add(mostarda)))
        .add(12, 12, 12)
        .add(panelIngredientesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(pepino)
          .add(alface))
        .add(18, 18, 18)
        .add(panelIngredientesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(picles)
          .add(barbecue))
        .addContainerGap(12, Short.MAX_VALUE))
    );
    panelIngredientesLayout.setVerticalGroup(
      panelIngredientesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(panelIngredientesLayout.createSequentialGroup()
        .add(panelIngredientesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(tomate)
          .add(cebola)
          .add(alface)
          .add(picles))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(panelIngredientesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(ketchup)
          .add(mostarda)
          .add(pepino)
          .add(barbecue)))
    );

    panelValorTotal.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor Total"));

    valorTotal.setColumns(20);
    valorTotal.setRows(5);
    jScrollPane1.setViewportView(valorTotal);

    org.jdesktop.layout.GroupLayout panelValorTotalLayout = new org.jdesktop.layout.GroupLayout(panelValorTotal);
    panelValorTotal.setLayout(panelValorTotalLayout);
    panelValorTotalLayout.setHorizontalGroup(
      panelValorTotalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(panelValorTotalLayout.createSequentialGroup()
        .addContainerGap()
        .add(jScrollPane1)
        .addContainerGap())
    );
    panelValorTotalLayout.setVerticalGroup(
      panelValorTotalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(panelValorTotalLayout.createSequentialGroup()
        .addContainerGap()
        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        .addContainerGap())
    );

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(panelIngredientes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .add(panelPedido, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .add(panelValorTotal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(panelPedido, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(panelIngredientes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
        .add(panelValorTotal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void lancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lancheActionPerformed
    if("selecione".equals((String)lanche.getSelectedItem())) {
      selecionarLanche("", 0.0);
    } else if("hamburguer".equals((String)lanche.getSelectedItem())) {
      selecionarLanche("hamburguer", 3.0);
    } else if("cheeseburguer".equals((String)lanche.getSelectedItem())) {
      selecionarLanche("cheeseburguer", 4.0);
    }
  }//GEN-LAST:event_lancheActionPerformed

  private void selecionarLanche(String descricao, double preco) {
    pedido.setLanche(descricao);
    pedido.setPrecoLanche(preco);
    
    gerarRelatorio();
  }
  
  private void pequenoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pequenoItemStateChanged
    selecionarBatata("pequeno", 1.0);
  }//GEN-LAST:event_pequenoItemStateChanged

  private void medioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_medioItemStateChanged
    selecionarBatata("médio", 1.5);
  }//GEN-LAST:event_medioItemStateChanged

  private void grandeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_grandeItemStateChanged
    selecionarBatata("grande", 2.0);
  }//GEN-LAST:event_grandeItemStateChanged

  private void selecionarBatata(String tamanho, double preco) {
    pedido.setBatataFrita(tamanho);
    pedido.setPrecoBatataFrita(preco);
    
    gerarRelatorio();
  }
  
  private void tomateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tomateItemStateChanged
    adicionarRemoverIngrediente(tomate);
  }//GEN-LAST:event_tomateItemStateChanged

  private void cebolaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cebolaItemStateChanged
    adicionarRemoverIngrediente(cebola);
  }//GEN-LAST:event_cebolaItemStateChanged

  private void alfaceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_alfaceItemStateChanged
    adicionarRemoverIngrediente(alface);
  }//GEN-LAST:event_alfaceItemStateChanged

  private void piclesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_piclesItemStateChanged
    adicionarRemoverIngrediente(picles);
  }//GEN-LAST:event_piclesItemStateChanged

  private void ketchupItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ketchupItemStateChanged
    adicionarRemoverIngrediente(ketchup);
  }//GEN-LAST:event_ketchupItemStateChanged

  private void mostardaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mostardaItemStateChanged
    adicionarRemoverIngrediente(mostarda);
  }//GEN-LAST:event_mostardaItemStateChanged

  private void pepinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepinoActionPerformed
    adicionarRemoverIngrediente(pepino);
  }//GEN-LAST:event_pepinoActionPerformed

  private void barbecueItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_barbecueItemStateChanged
    adicionarRemoverIngrediente(barbecue);
  }//GEN-LAST:event_barbecueItemStateChanged

  private void adicionarRemoverIngrediente(javax.swing.JCheckBox ingrediente) {
    if(ingrediente.isSelected()) {
      pedido.setIngredientes(pedido.getIngredientes() + ingrediente.getText() + " ");
      pedido.setPrecoIngredientes(pedido.getPrecoIngredientes() + 0.5);
    } else {
      pedido.setIngredientes(pedido.getIngredientes().replaceAll(ingrediente.getText() + " ", ""));
      pedido.setPrecoIngredientes(pedido.getPrecoIngredientes() - 0.5);
    }
    
    gerarRelatorio();
  }
  
  private void gerarRelatorio() {
    String texto = pedido.getLanche() + ": R$" + pedido.getPrecoLanche()
            + "\nBatata frita " + pedido.getBatataFrita() + ": R$" + pedido.getPrecoBatataFrita()
            + "\n" + pedido.getIngredientes() + ": R$" + pedido.getPrecoIngredientes()
            + "\n\nTotal: R$" + pedido.getTotal();
    
    valorTotal.setText(texto);
  }
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TelaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TelaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TelaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TelaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new TelaPedido().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox alface;
  private javax.swing.JCheckBox barbecue;
  private javax.swing.JCheckBox cebola;
  private javax.swing.JRadioButton grande;
  private javax.swing.ButtonGroup grupoBatataFrita;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JCheckBox ketchup;
  private javax.swing.JComboBox lanche;
  private javax.swing.JRadioButton medio;
  private javax.swing.JCheckBox mostarda;
  private javax.swing.JPanel panelIngredientes;
  private javax.swing.JPanel panelPedido;
  private javax.swing.JPanel panelValorTotal;
  private javax.swing.JCheckBox pepino;
  private javax.swing.JRadioButton pequeno;
  private javax.swing.JCheckBox picles;
  private javax.swing.JCheckBox tomate;
  private javax.swing.JTextArea valorTotal;
  // End of variables declaration//GEN-END:variables
}
